In [2]:
import numpy as np

## Data Types and Attributes

Numpy's main data type is N-dimensional array (ndarray)

In [3]:
a1 = np.array([1,2,3])
a1.shape

(3,)

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.5,3],[4,5.6,6]])
a2.shape

(2, 3)

In [6]:
a3 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
a3.shape

(3, 2, 3)

## Creating a dataframe from a numpy array

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(a2)
df

     0    1    2
0  1.0  2.5  3.0
1  4.0  5.6  6.0

## Creating numpy arrays

In [11]:
arr = np.array(["123", "abc", 123])
arr.dtype

dtype('<U21')

In [9]:
sample_array = np.array([1,2,3])

In [10]:
ones = np.ones((3,3,3), dtype=int)
ones

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [11]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [14]:
random_array = np.random.randint(0, 100, size=(3,3,3))
random_array

array([[[23, 53, 37],
        [55, 77, 57],
        [65, 91, 20]],

       [[85, 48, 15],
        [13, 78, 10],
        [62, 81, 57]],

       [[99, 91,  9],
        [ 3, 22, 19],
        [86, 50, 92]]])

## Viewing Arrays

### checking unique elements of an array

In [22]:
arr = np.random.randint(0,5, size=(2,2))
arr

array([[0, 4],
       [1, 1]])

In [23]:
np.unique(arr)

array([0, 1, 4])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [16]:
a3[:3:2, :3:2, :3:2]

array([[[ 1,  3]],

       [[13, 15]]])

In [17]:
a4 = np.random.randint(0,10, size=(2,3,4,5))
a4

array([[[[4, 9, 4, 4, 6],
         [9, 0, 7, 1, 8],
         [5, 7, 2, 6, 6],
         [5, 2, 6, 7, 7]],

        [[9, 5, 4, 0, 2],
         [3, 4, 9, 2, 0],
         [2, 2, 4, 2, 4],
         [7, 6, 8, 6, 6]],

        [[8, 2, 7, 0, 8],
         [3, 5, 4, 0, 7],
         [7, 2, 2, 2, 7],
         [9, 6, 7, 8, 7]]],


       [[[8, 4, 3, 7, 4],
         [3, 7, 4, 8, 4],
         [0, 7, 8, 9, 1],
         [3, 8, 7, 4, 2]],

        [[0, 3, 6, 8, 7],
         [8, 5, 5, 8, 7],
         [3, 2, 7, 1, 3],
         [8, 4, 9, 7, 0]],

        [[8, 1, 7, 4, 1],
         [5, 9, 9, 5, 2],
         [5, 7, 2, 0, 1],
         [5, 4, 0, 4, 4]]]], dtype=int32)

In [18]:
a4[1,1,0]

array([0, 3, 6, 8, 7], dtype=int32)

## Manipulating and Comparing Arrays

### arithmetic

In [19]:
a1

array([1, 2, 3])

In [20]:
ones = np.ones((1,3), dtype=int)
ones

array([[1, 1, 1]])

In [21]:
a1 + ones

array([[2, 3, 4]])

In [22]:
a2

array([[1. , 2.5, 3. ],
       [4. , 5.6, 6. ]])

In [23]:
a2 + ones

array([[2. , 3.5, 4. ],
       [5. , 6.6, 7. ]])

In [25]:
a2 * a1

array([[ 1. ,  5. ,  9. ],
       [ 4. , 11.2, 18. ]])

In [26]:
np.subtract(a1,a2)

array([[ 0. , -0.5,  0. ],
       [-3. , -3.6, -3. ]])

In [28]:
np.divide(a1,a2)

array([[1.        , 0.8       , 1.        ],
       [0.25      , 0.35714286, 0.5       ]])

In [31]:
np.mod(a1,2)

array([1, 0, 1])

In [32]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
performing the same operation on a number of things

In [80]:
list1 = [1,2,3]

In [81]:
sum(list1)

6

In [82]:
np.sum(list1)

np.int64(6)

In [83]:
massiveArray = np.random.random(100000)
massiveArray.size

100000

In [84]:
%timeit sum(massiveArray)
%timeit np.sum(massiveArray)

4.44 ms ± 47.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20.1 μs ± 216 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

## Reshaping and Transposing

In [85]:
a2.shape

(2, 3)

In [24]:
a3.shape

(3, 2, 3)

In [36]:
arr = np.array([10,20])
arr = arr.T
arr

array([10, 20])

In [87]:
a2_reshaped = a2.reshape(3,2,1)

In [88]:
a2_reshaped * a3

array([[[  1. ,   2. ,   3. ],
        [ 10. ,  12.5,  15. ]],

       [[ 21. ,  24. ,  27. ],
        [ 40. ,  44. ,  48. ]],

       [[ 72.8,  78.4,  84. ],
        [ 96. , 102. , 108. ]]])

In [89]:
a2.shape

(2, 3)

In [90]:
a2.T.shape

(3, 2)

## Dot Product Example

In [42]:
np.random.seed(0)
sales = np.random.randint(0,20, size=(5,3))
sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [46]:
sales_df = pd.DataFrame(sales, 
                        index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], 
                        columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
sales_df

           Almond Butter  Peanut Butter  Cashew Butter
Monday                12             15              0
Tuesday                3              3              7
Wednesday              9             19             18
Thursday               4              6             12
Friday                 1              6              7

In [93]:
prices = np.array([10, 8, 12])
prices.shape

(3,)

In [94]:
prices_df = pd.DataFrame(prices.reshape(1,3), 
                         index=["Price"], 
                         columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
prices_df

       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [95]:
sales_df["Total"] = np.dot(sales_df, prices_df.T)
sales_df

           Almond Butter  Peanut Butter  Cashew Butter  Total
Monday                12             15              0    240
Tuesday                3              3              7    138
Wednesday              9             19             18    458
Thursday               4              6             12    232
Friday                 1              6              7    142

## Comparison Operators

In [96]:
# same as python operators

## Sorting

In [97]:
random_array = np.random.randint(0, 100, size=(5, 5))
random_array

array([[87, 46, 88, 81, 37],
       [25, 77, 72,  9, 20],
       [80, 69, 79, 47, 64],
       [82, 99, 88, 49, 29],
       [19, 19, 14, 39, 32]], dtype=int32)

In [47]:
np.sort(random_array)

array([[[23, 37, 53],
        [55, 57, 77],
        [20, 65, 91]],

       [[15, 48, 85],
        [10, 13, 78],
        [57, 62, 81]],

       [[ 9, 91, 99],
        [ 3, 19, 22],
        [50, 86, 92]]])

In [99]:
np.argsort(random_array)

array([[4, 1, 3, 0, 2],
       [3, 4, 0, 2, 1],
       [3, 4, 1, 2, 0],
       [4, 3, 0, 2, 1],
       [2, 0, 1, 4, 3]])

In [105]:
random_array

array([[87, 46, 88, 81, 37],
       [25, 77, 72,  9, 20],
       [80, 69, 79, 47, 64],
       [82, 99, 88, 49, 29],
       [19, 19, 14, 39, 32]], dtype=int32)

In [106]:
np.argmin(random_array), np.argmax(random_array)

(np.int64(8), np.int64(16))

## Practical Example

<img src = "numpy-images/panda.png"/>

### turning an image to a numpy array

In [112]:
from matplotlib.image import imread
panda = imread("numpy-images/panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0.05098039, 0.03137255],
        ...,
        [0.02745098, 0.02745098, 0.03529412],
        [0.02745098, 0.02745098, 0.03529412],
        [0.02745098, 0.02745098, 0.03529412]],

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.12156863, 0.0627451 , 0.04313726],
        ...,
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255]],

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.12156863, 0.0627451 , 0.04313726],
        ...,
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255]]],
      shape=(2330, 3500, 3), dtype=float32)